### ISSUE TITLE
Support for loading transformers written in ESM

### ISSUE THREAD

**Issue by uhyo** [anc95/jest-chain-transform#11]
Hello, thank you for the great tool! 🙂 

Recently Jest supports loading transformers written in ESM through [the `requireOrImportModule` util](https://github.com/jestjs/jest/blob/8bbe2a34a8a7979d71ece3fadc6006df3e607d9f/packages/jest-transform/src/ScriptTransformer.ts#L281).

It would be great if jest-chain-transform could support such loaders too.

Downside is that this would require `createTransformer` function to be an async function, which is supported only by Jest >= 29.4, 😢

**Comment by anc95** [comment]
Noted. will look into this and try to support ESM loader

**Comment by anc95** [comment]
0.0.6 supports the ESM transformer to be chained.

Jest ESM is still under experiment. Please refer to https://jestjs.io/docs/ecmascript-modules.

An [example](https://github.com/anc95/jest-chain-transform/tree/main/src/example/babel-jest-esm)

**Comment by uhyo** [comment]
Thanks for the good news! :tada: I'll check.
