### ISSUE TITLE
0.0.6 main script points to unpublished files

### ISSUE THREAD

**Issue by stabback** [anc95/jest-chain-transform#12]
It looks like the build script changed in 0.0.6 to output to `dist` instead of `lib`.  This `dist` folder isn't published to npm, so the package fails to resolve the `main` script in package.json.

**Comment by anc95** [comment]
my bad. working on this now

**Comment by anc95** [comment]
<img width="813" alt="image" src="https://github.com/anc95/jest-chain-transform/assets/13167934/8567a5db-9977-46d4-896a-663147b16383">
0.0.7 includes dist. Please try to update
