### ISSUE TITLE
Module is not compiled with npm install

### ISSUE THREAD

**Issue by bamthomas** [anc95/jest-chain-transform#2]
when installing the module (with `npm install`) the module is not compiled, there is no `lib` directory :

```
Error: Cannot find module '/home/dev/src/sveltekit-jest-example/node_modules/jest-chain-transform/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

we're using it here : https://github.com/iroco-co/sveltekit-jest-example
npm version : 6.14.11 on ubuntu 20.04

Not sure what is causing this behavior but if I find I will make a PR

**Comment by sebinsua** [comment]
In the absence of  `.npmignore` or `package.json#files`, `npm publish` uses the `.gitignore` to decide what to include in the package.

In this case, it's broken because `lib` is configured within `.gitignore`.

**Comment by anc95** [comment]
I just publish version 0.0.4, and this issue should be fixed, Thanks for your issue.
